import ruby from '../images/ruby.jpg'
import pudding from '../images/pudding.png'
import motorHome from '../images/motorHome.jpg'
import goldenToilet from '../images/GoldenToilet.jpg'
import watch from '../images/DiamondWatch.jpg'

export const mockData = [
    { "id": 1, "name": "Ruby Slippers", "shortDescription": "An impressive pair of slippersfeaturingthousands of real rubies", "longDescription": "Harry Winston has carefully crafted these fantastic shoes. Each pair boasts a total of 4,600 gemstones including 1,350 carats of premium Harry Winston has carefully crafted these fantastic shoes. Each pair boasts a total of 4,600 gemstones including 1,350 carats of premium Harry Winston has carefully crafted these fantastic shoes. Each pair boasts a total of 4,600 gemstones including 1,350 carats of premium these slippers are though.", "imageLink": "https://raw.githubusercontent.com/jeff-lent/Alisnobba/main/Capstone/ActualRubyRubySlippers.jpg", "price": 6.8475E7 },
    { "id": 2, "name": "Chocolate Pudding", "shortDescription": "This better bethe bestpudding youever ate!", "longDescription": "Harry Winston has carefully crafted these fantastic shoes. Each pair boasts a total of 4,600 gemstones including 1,350 carats of premium Harry Winston has carefully crafted these fantastic shoes. Each pair boasts a total of 4,600 gemstones including 1,350 carats of premium Harry Winston has carefully crafted these fantastic shoes. Each pair boasts a total of 4,600 gemstones including 1,350 carats of premium these slippers are though.", "imageLink": "https://raw.githubusercontent.com/jeff-lent/Alisnobba/main/Capstone/ChocolatePudding.png", "price": 7.9885155E7 },
    { "id": 3, "name": "Diamond Watch", "shortDescription": "Thisintentionallyoutrageoustime piecetells time justas well as thephone in yourpocket!", "longDescription": "Harry Winston has carefully crafted these fantastic shoes. Each pair boasts a total of 4,600 gemstones including 1,350 carats of premium Harry Winston has carefully crafted these fantastic shoes. Each pair boasts a total of 4,600 gemstones including 1,350 carats of premium Harry Winston has carefully crafted these fantastic shoes. Each pair boasts a total of 4,600 gemstones including 1,350 carats of premium these slippers are though.", "imageLink": "https://raw.githubusercontent.com/jeff-lent/Alisnobba/main/Capstone/DiamondWatch.jpg", "price": 5874537.45 },
    { "id": 4, "name": "Golden Toilet", "shortDescription": "The perfectthrone for ourdiscerningbillionairecustomers!", "longDescription": "Harry Winston has carefully crafted these fantastic shoes. Each pair boasts a total of 4,600 gemstones including 1,350 carats of premium Harry Winston has carefully crafted these fantastic shoes. Each pair boasts a total of 4,600 gemstones including 1,350 carats of premium Harry Winston has carefully crafted these fantastic shoes. Each pair boasts a total of 4,600 gemstones including 1,350 carats of premium these slippers are though.", "imageLink": "https://raw.githubusercontent.com/jeff-lent/Alisnobba/main/Capstone/GoldenToilet.jpg", "price": 5.6746543578E9 },
    { "id": 5, "name": "Land Yacht MotorHome", "shortDescription": "All the luxuryof a yacht,but withwheels and areally weirdwind screen!", "longDescription": "Harry Winston has carefully crafted these fantastic shoes. Each pair boasts a total of 4,600 gemstones including 1,350 carats of premium Harry Winston has carefully crafted these fantastic shoes. Each pair boasts a total of 4,600 gemstones including 1,350 carats of premium Harry Winston has carefully crafted these fantastic shoes. Each pair boasts a total of 4,600 gemstones including 1,350 carats of premium these slippers are though.", "imageLink": "https://raw.githubusercontent.com/jeff-lent/Alisnobba/main/Capstone/LandYachtMotorHome.jpg", "price": 4.78572316574E8 }
]
